[build]
  command = "npm run build"
  publish="/assignment6/build"
  base = "/assignment6"

[[redirects]]
  from = "/api/*"
  to = "https://favorite-members-app-json-server.herokuapp.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200