[build]
  command = "npm run build"
  publish="path-to-react-app/build"
  base = "path-to-react-app"

[[redirects]]
  from = "/api/*"
  to = "https://favorite-members-app-json-server.herokuapp.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200